name: Test Build on BinderHub

on:
  push:
  workflow_dispatch:

jobs:
  test-build:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: 2i2c-org/clinder@HEAD
        with:
          hub-url: https://binder.projectpythia.org/
          repo: ProjectPythia/radar-cookbook
          ref: HEAD
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install MyST Markdown
        run: npm install -g mystmd
      # This will fail if it picks up the CI variable locally
      - name: Build MyST Project
        run: myst build --site --strict --execute
        working-directory: test
